version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install
      - run: npm test

# Orchestrate our job run sequence
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
